Smart-Attendance-Management-System-Using-Facial-Recognition-main/CollegeAutomation/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
   url(r'^',include('generalzone.urls')),
url(r'^studentzone/',include(('studentzone.urls','studentzone'),namespace='studentzone')),
url(r'^teachers/',include(('teachers.urls','teachers'),namespace='teachers')),
    url(r'^director/',include(('director.urls','director'),namespace='director')),
   ]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

Smart-Attendance-Management-System-Using-Facial-Recognition-main/director/urls.py
from django.conf.urls import url
from . import views
urlpatterns=[
    url(r'^$',views.direchome,name='direchome'),
    url(r'^createtable',views.createtable,name='createtable'),
    url(r'^savetable',views.savetable,name='savetable'),
    url(r'^deletedepartment/(?P<id>\d+)$',views.deletedepartment,name='deletedepartment'),
    url(r'^createsubject',views.createsubject,name='createsubject'),
    url(r'^showsubject/(?P<id>\d+)$',views.showsubject,name='showsubject'),
    url(r'^savesubject',views.savesubject,name='savesubject'),

]

Smart-Attendance-Management-System-Using-Facial-Recognition-main/studentzone/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
url(r'^userzone',views.userzone,name='userzone'),
url(r'^discussion', views.discussion, name='discussion'),
url(r'^searchsolution', views.searchsolution, name='searchsolution'),
url(r'^complainlog', views.complainlog, name='complainlog'),
url(r'^changepassword', views.changepassword, name='changepassword'),
url(r'^postquestion', views.postquestion, name='postquestion'),
url(r'^answer/(?P<qid>\d+)$', views.answer, name='answer'),
url(r'^postanswer', views.postanswer, name='postanswer'),
url(r'^viewanswer/(?P<qid>\d+)$', views.viewanswer, name='viewanswer'),
url(r'^changepwd', views.changepwd, name='changepwd'),
url(r'^savecomplain', views.savecomplain, name='savecomplain'),
url(r'^answer/(?P<qid>\d+)$',views.answer,name='answer'),
url(r'^postanswer',views.postanswer,name='postanswer'),
url(r'^viewanswer/(?P<qid>\d+)$',views.viewanswer,name='viewanswer'),
]

Smart-Attendance-Management-System-Using-Facial-Recognition-main/studentzone/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    qid=models.AutoField(primary_key=True)
    questiontext=models.TextField()
    askedby=models.CharField(max_length=50)
    pasteddate=models.CharField(max_length=30)
class Answer(models.Model):
    aid=models.AutoField(primary_key=True)
    answertext=models.TextField()
    answeredby=models.CharField(max_length=50)
    qid=models.IntegerField()
    answereddate=models.CharField(max_length=30)
class Complain(models.Model):
    name=models.CharField(max_length=50)
    gender=models.CharField(max_length=6)
    address=models.TextField()
    rollno=models.CharField(max_length=15)
    contactno=models.CharField(max_length=15)
    subject=models.CharField(max_length=200)
    complaintext=models.TextField()
    complaindate=models.CharField(max_length=30)

Smart-Attendance-Management-System-Using-Facial-Recognition-main/studentzone/views.py
from django.shortcuts import render,redirect
from generalzone.models import StudentInfo,LoginInfo
from .models import Question,Answer,Complain
from director.models import Subject
import os
import datetime,openpyxl
import datetime
# Create your views here.
def userzone(request):
    if request.session['userid']:
        x=StudentInfo.objects.get(rollno=request.session['userid'])
        subjectCode=Subject.objects.filter(semester=x.semester)
        now = datetime.datetime.now()
        today = now.day
        month = now.month
        year = now.year
        mn = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October',
              'November', 'December']
        r =list()
        s=list()
        for p in subjectCode:
            #print(str(p.subjectcode))
            r.append(str(p.subjectcode))
            count=0
            if not os.path.isdir("./media/Attendances/Semester " + str(x.semester) + "/" + str(p.subjectcode) + "/"):
                print(os.makedirs("./media/Attendances/Semester " + str(x.semester) + "/" + str(p.subjectcode) + "/"))
                #print('A')
            for m in mn:
                #print(m)
                #print('A'+str(os.path.isfile(os.path.join("./media/Attendances/Semester " + str(x.semester) + "/" + str(p.subjectcode) + "/",str(m) + '.xlsx'))))
                if os.path.isfile(os.path.join("./media/Attendances/Semester " + str(x.semester) + "/" + str(p.subjectcode) + "/",str(m) + '.xlsx')):
                    #print(os.path.isfile(os.path.join("./media/Attendances/Semester " + str(x.semester) + "/" + str(p) + "/",str(m) + '.xlsx')))
                    wb = openpyxl.load_workbook(
                        os.path.join("./media/Attendances/Semester " + str(x.semester) + "/" + str(p.subjectcode) + "/",
                                     str(m) + '.xlsx'))
                    worksheet = wb.active
                    #print(p.subjectcode)

                    c=0
                    for row in worksheet.iter_rows():
                        #print('X')
                        c=c+1
                        #print(c)
                       # print(row[0])
                        #print(row[0].value)
                        if str(row[0].value)==str(x.rollno):
                                #print('B')
                                if worksheet.cell(row=int(c),column=35).value is not None:
                                    count=count+int(worksheet.cell(row=int(c),column=35).value)
                                    #print('B'+str(count))
            s.append(count)
            #print('C'+str(count))
        return render(request,'userzone.html',{'r':r,'s':s,'subjectCode':subjectCode})
    else:
        return render(request('index.html'))
def discussion(request):
    if request.session['userid']:
        ques = Question.objects.all()
        return render(request, 'discussion.html', {'ques': ques})
    else:
        return render(request('index.html'))
def complainlog(request):
    if request.session['userid']:
        return render(request,'complainlog.html')
    else:
        return render(request('index.html'))
def searchsolution(request):
    if request.session['userid']:
        return render(request,'searchsolution.html')
    else:
        return render(request('index.html'))
def changepassword(request):
    if request.session['userid']:
        return render(request,'changepassword.html')
    else:
        return render(request('index.html'))
def postanswer(request):
    if request.session['userid']:
        rollno=request.session.get('userid')
        student=StudentInfo.objects.get(rollno=rollno)
        answeredby=student.name
        qid=request.POST['qid']
        answertext=request.POST['answertext']
        answereddate=datetime.datetime.now().strftime('%Y/%m/%d')
        a=Answer(answertext=answertext,answeredby=answeredby,qid=qid,answereddate=answereddate)
        a.save()
        return redirect('studentzone:discussion')
    else:
        return render(request,'index.html')

def postquestion(request):
        if request.session['userid']:
            rollno= request.session.get('userid')
            customer = StudentInfo.objects.get(rollno=rollno)
            askedby = customer.name
            questiontext = request.POST['questiontext']
            pasteddate = datetime.datetime.now().strftime('%Y/%m/%d')
            q = Question(questiontext=questiontext, askedby=askedby, pasteddate=pasteddate)
            q.save()
            q=Question.objects.all()
            return render(request, 'discussion.html', {'ques': q})
        else:
            return render(request, 'index.html')
def answer(request,qid):
    if request.session['userid']:
        return render(request,'answer.html',{'qid':qid})
    else:
        return render(request,'index.html')
def viewanswer(request,qid):
    if request.session['userid']:
        ans=Answer.objects.filter(qid=qid)
        return render(request,'viewanswer.html',{'ans':ans})
    else:
        return render(request,'index.html')
def changepwd(request):
    if request.session['userid']:
        userid=request.session.get('userid')
        oldpassword=request.POST['oldpassword']
        newpassword=request.POST['newpassword']
        confirmpassword=request.POST['confirmpassword']
        if newpassword != confirmpassword:
            msg="newpassword and confirmpassword should match"
            return render(request,'changepassword.html',{'msg':msg})
        else:
            user=LoginInfo.objects.get(userid=userid,password=oldpassword)
            if user is not None:
                li=LoginInfo(password=newpassword,userid=userid,usertype='student')
                li.save()
                return render(request,'index.html')
            else:
                msg="old password does not msg"
                return render(request, 'changepassword.html', {'msg': msg})
    else:
        return render(request,'index.html')
def savecomplain(request):
    if request.session['userid']:
        rollno=request.session.get('userid')
        customer=StudentInfo.objects.get(rollno=rollno)
        name=customer.name
        gender=customer.gender
        address=customer.address
        contactno=customer.contactno
        subject=request.POST['subject']
        complaintext=request.POST['complaintext']
        complaindate=datetime.datetime.now().strftime('%Y/%m/%d')
        com=Complain(name=name,gender=gender,address=address,contactno=contactno,subject=subject,complaintext=complaintext,rollno=rollno,complaindate=complaindate)
        com.save()
        return redirect('studentzone:userhome')
    else:
        return render(request,'login.html')
def answer(request,qid):
    if request.session['userid']:
        return render(request,'answer.html',{'qid':qid})
    else:
        return render(request,'login.html')
def postanswer(request):
    if request.session['userid']:
        rollno=request.session.get('userid')
        customer=StudentInfo.objects.get(rollno=rollno)
        answertext=request.POST['answertext']
        qid=request.POST['qid']
        answeredby=customer.name
        answereddate=datetime.datetime.now().strftime('%Y/%m/%d')
        a=Answer(answertext=answertext,answeredby=answeredby,qid=qid,answereddate=answereddate)
        a.save()
        return redirect('studentzone:discussion')
    else:
        return render(request,'login.html')
def viewanswer(request,qid):
    if request.session['userid']:
        ans=Answer.objects.filter(qid=qid)
        return render(request,'viewanswer.html',{'ans':ans})
    else:
        return render(request,'login.html')

Smart-Attendance-Management-System-Using-Facial-Recognition-main/studentzone/templates/Logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

Smart-Attendance-Management-System-Using-Facial-Recognition-main/studentzone/templates/answer.html
<!DOCTYPE html>
<html lang="en">
{% load static%}
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>REC Sonbhadra</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <link href="{% static 'css/style.css'%}" type="text/css" rel="stylesheet" >
    <style >
    .bs-example{
       // margin-top: 20px;
    }
    .top-content-style img {
    -webkit-border-radius: 50%;
    -o-border-radius: 50%;
    -ms-border-radius: 50%;
    -moz-border-radius: 50%;
    border-radius: 50%;
}
    p.legend {
    color: #4e4d4d;
    font-size: 24px;
    text-align: center;
    margin-bottom: 1.2em;
}
.input span {
    position: absolute;
    display: block;
    color: #1cc7d0;
    left: 10px;
    top: 12px;
    font-size: 16px;
}
.fa {
    display: inline-block;
    font: normal normal normal 14px/1 FontAwesome;
    font-size: inherit;
    text-rendering: auto;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}
.input input {
    width: 100%;
    padding: 13px 10px 13px 34px;
    display: block;
    border: none;
    border: 1px solid #1cc7d0;
    color: #000;
    box-sizing: border-box;
    font-size: 13px;
    outline: none;
    letter-spacing: 1px;
    background: #fff;
    -webkit-box-shadow: 2px 5px 16px 2px rgba(16, 16, 16, 0.18);
    -moz-box-shadow: 2px 5px 16px 2px rgba(16, 16, 16, 0.18);
    box-shadow: 2px 5px 16px 2px rgba(16, 16, 16, 0.18);
}
.top-content-style {
    padding: 2vw 4vw 4vw;
    background: #1cc7d0;
}
.submit {
    width: 45px;
    height: 45px;
    display: block;
    margin: 2.5em auto 0;
    background: #1cc7d0;
    -webkit-border-radius: 10px;
    -o-border-radius: 10px;
    -ms-border-radius: 10px;
    -moz-border-radius: 10px;
    border-radius: 10px;
    border: none;
    cursor: pointer;
    -webkit-transition: 0.5s all;
    -o-transition: 0.5s all;
    -moz-transition: 0.5s all;
    -ms-transition: 0.5s all;
    transition: 0.5s all;
}
.input {
    position: relative;
    margin: 20px auto;
    width: 100%;
}
    form {
    background: #ffff;
    padding: 2em;
    -webkit-box-shadow: 2px 5px 16px 2px rgba(16, 16, 16, 0.18);
    -moz-box-shadow: 2px 5px 16px 2px rgba(16, 16, 16, 0.18);
    box-shadow: 2px 5px 16px 2px rgba(16, 16, 16, 0.18);
    margin: -2.5em 2.5em 2em;
    -webkit-border-radius: 4px;
    -o-border-radius: 4px;
    -ms-border-radius: 4px;
    -moz-border-radius: 4px;
    border-radius: 4px;
}


.bg-content-w3pvt {
    max-width: 400px;
    margin: 25px;
    background: #fff;
    }
</style>
</head>
<body>
<div class="bs-example">


    <nav class="navbar navbar-expand-md navbar-light bg-info">
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav">
                <a href="{%url 'studentzone:userzone'%}"class="nav-item nav-link active">User Home</a>
            <a href="{%url 'studentzone:discussion'%}" class="nav-item nav-link ">Discussion</a>
            <a href="{%url 'studentzone:searchsolution'%}" class="nav-item nav-link ">Search Solutions</a>
           <a href="{%url 'studentzone:complainlog'%}" class="nav-item nav-link">Complain Log</a>
           <a href="{%url 'studentzone:changepassword'%}"class="nav-item nav-link ">Change Password</a>
           <a href="{%url 'index'%}" class="nav-item nav-link ">Log Out</a>
            </div>
            <div class="navbar-nav ml-auto">
                   </div>
        </div>

    </nav>


<div class="container-fluid" style="min-height:50px;">
<div class="row" style="min-height:400px;background-color:black;">
<br/>
    <br/>
<div class="row" id="parent">

     <div class="col-sm-4" id="left">
<marquee direction="up" height="400px" onmouseover="stop()" onmouseout="start()">
             {% for n in nf %}
                  <div style="background:white;border:2px solid black;margin-top:3px;">
             <span style="text-align:center">
             <p style="color:black;font-size:20px;">{{n.notificationtext}}</p>
             <p>{{n.posteddate}}</p>
                 </span>
                     </div>
             {% endfor%}
                 </marquee>
    </div>
<div class="col-sm-8" id="main" style="background-color:;">
  <center>
       <!--form action="{% url 'studentzone:postanswer' %}" method="post">
            {% csrf_token%}
            <h2 style="text-align:center;color:blue;">
                Discussion Form
            </h2>
            <table border="1" style="margin:0 auto; width:50%">
                <tr>
                    <td>Enter Answer</td>
                    <td>
                        <textarea name="answertext" required style="height:100px;resize:none;"></textarea>
                    </td>
                </tr>
                <tr>
                    <td><input type="hidden" name="qid" value="{{qid}}"/></td>
                    <td><input type="submit" value="Post"/> </td>
                </tr>
            </table>
        </form-->
      <br/>
      <br/>
      <h2 style="text-align:center;">
                Answer
            </h2>
      <form class="form-horizontal " action="{%url 'studentzone:postanswer' %}" method="post">
{%csrf_token%}

<br/>
            <br/>
             <div class="form-group">
                    <div class="row">
                        <label class="col-sm-3"for="questiontext"><b>Enter Answer:</b></label>
  <textarea class="form-control col-sm-5" rows="5" id="questiontext"  name="answertext" required placeholder="Enter Answer Text" style="resize:none;"></textarea>
</div>
                </div>
           <div class="form-group">
                    <div class="row">
  <input type="hidden" class="form-control col-sm-5" rows="5"  name="qid" value="{{qid}}">
</div>
                </div>




                    <div class="col-sm-5">
                        <button type="submit" class="btn btn-success" value="POST">
                            Submit
                        </button>
                    </div>
                </div>
                </div>
        </form>

  </center>

</div>

</div>
    <div class="row" id="footer">
        <div class="col-sm-6" id="lfooter">
            Copyright&copy; &nbsp; to CPO
        </div>
          <div class="col-sm-6" id="rfooter">
          Developed by
        </div>
    </div>
</div>
</div>
</div>
</body>
</html>

Smart-Attendance-Management-System-Using-Facial-Recognition-main/studentzone/templates/discussion.html
<!DOCTYPE html>
<html lang="en">
{% load static%}
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>REC Sonbhadra</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <link href="{% static 'css/style.css'%}" type="text/css" rel="stylesheet" >
    <style >
    .bs-example{
       // margin-top: 20px;
    }
    .top-content-style img {
    -webkit-border-radius: 50%;
    -o-border-radius: 50%;
    -ms-border-radius: 50%;
    -moz-border-radius: 50%;
    border-radius: 50%;
}
    p.legend {
    color: #4e4d4d;
    font-size: 24px;
    text-align: center;
    margin-bottom: 1.2em;
}
.input span {
    position: absolute;
    display: block;
    color: #1cc7d0;
    left: 10px;
    top: 12px;
    font-size: 16px;
}
.fa {
    display: inline-block;
    font: normal normal normal 14px/1 FontAwesome;
    font-size: inherit;
    text-rendering: auto;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}
.input input {
    width: 100%;
    padding: 13px 10px 13px 34px;
    display: block;
    border: none;
    border: 1px solid #1cc7d0;
    color: #000;
    box-sizing: border-box;
    font-size: 13px;
    outline: none;
    letter-spacing: 1px;
    background: #fff;
    -webkit-box-shadow: 2px 5px 16px 2px rgba(16, 16, 16, 0.18);
    -moz-box-shadow: 2px 5px 16px 2px rgba(16, 16, 16, 0.18);
    box-shadow: 2px 5px 16px 2px rgba(16, 16, 16, 0.18);
}
.top-content-style {
    padding: 2vw 4vw 4vw;
    background: #1cc7d0;
}
.submit {
    width: 45px;
    height: 45px;
    display: block;
    margin: 2.5em auto 0;
    background: #1cc7d0;
    -webkit-border-radius: 10px;
    -o-border-radius: 10px;
    -ms-border-radius: 10px;
    -moz-border-radius: 10px;
    border-radius: 10px;
    border: none;
    cursor: pointer;
    -webkit-transition: 0.5s all;
    -o-transition: 0.5s all;
    -moz-transition: 0.5s all;
    -ms-transition: 0.5s all;
    transition: 0.5s all;
}
.input {
    position: relative;
    margin: 20px auto;
    width: 100%;
}
    form {
    background: #ffff;
    padding: 2em;
    -webkit-box-shadow: 2px 5px 16px 2px rgba(16, 16, 16, 0.18);
    -moz-box-shadow: 2px 5px 16px 2px rgba(16, 16, 16, 0.18);
    box-shadow: 2px 5px 16px 2px rgba(16, 16, 16, 0.18);
    margin: -2.5em 2.5em 2em;
    -webkit-border-radius: 4px;
    -o-border-radius: 4px;
    -ms-border-radius: 4px;
    -moz-border-radius: 4px;
    border-radius: 4px;
}


.bg-content-w3pvt {
    max-width: 400px;
    margin: 25px;
    background: #fff;
    }
</style>
</head>
<body>
<div class="bs-example">


    <nav class="navbar navbar-expand-md navbar-light bg-info">
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav">
                <a href="{%url 'studentzone:userzone'%}"class="nav-item nav-link active">User Home</a>
            <a href="{%url 'studentzone:discussion'%}" class="nav-item nav-link ">Discussion</a>
            <a href="{%url 'studentzone:searchsolution'%}" class="nav-item nav-link ">Search Solutions</a>
           <a href="{%url 'studentzone:complainlog'%}" class="nav-item nav-link">Complain Log</a>
           <a href="{%url 'studentzone:changepassword'%}"class="nav-item nav-link ">Change Password</a>
           <a href="{%url 'index'%}" class="nav-item nav-link ">Log Out</a>
            </div>
            <div class="navbar-nav ml-auto">
                   </div>
        </div>

    </nav>


<div class="container-fluid" style="min-height:50px;">
<div class="row" style="min-height:400px;background-color:black;">

<div class="row" id="parent">

     <div class="col-sm-4" id="left">

    </div>
<div class="col-sm-8" id="main" style="background-color:;">
  <center>

             <h2 style="text-align:center;color:blue;">Discussion Forum</h2>
    <form class="form-horizontal " action="{%url 'studentzone:postquestion' %}" method="post">
{%csrf_token%}

<br/>
            <br/>
             <div class="form-group">
                    <div class="row">
                        <label class="col-sm-3"for="questiontext"><b>Enter Question:</b></label>
  <textarea class="form-control col-sm-5" rows="5" id="questiontext"  name="questiontext" required placeholder="Enter Question Text" style="resize:none;"></textarea>
</div>
                </div>

             <div class="form-group">
                    <div class="row">


                        <div class="checkbox col-sm-3">


</div>

                    <div class="col-sm-5">
                        <button type="submit" class="btn btn-success" value="POST">
                            Submit
                        </button>
                    </div>
                </div>
                </div>
        </form>



        <table  class="table  " style="margin:0px auto;">
            <thead class="table-dark">
            <tr>
                <th>Question</th>
                <th>Asked By</th>
                <th>posted Date</th>
                <th>post answer</th>
                <th>View Answer</th>
            </tr>
            </thead>
            {% for q in ques %}
            <tbody class="table-hover">
            <tr class="table-success " >
                <td>{{q.questiontext}}</td>
                <td>{{q.askedby}}</td>
                <td>{{q.posteddate}}</td>
                <td ><a style="font-weight:bold;" href="{% url 'studentzone:answer' q.qid %}">Post</a></td>
                <td><a style="font-weight:bold;"  href="{% url 'studentzone:viewanswer' q.qid %}">View</a></td>

            </tr>
            </tbody>
            {% endfor%}
        </table>

  </center>

</div>

</div>
    <div class="row" id="footer">
        <div class="col-sm-6" id="lfooter">
            Copyright&copy; &nbsp; to CPO
        </div>
          <div class="col-sm-6" id="rfooter">
          Developed by
        </div>
    </div>
</div>
</div>
</div>
</body>
</html>