Smart-Attendance-Management-System-Using-Facial-Recognition-main/CollegeAutomation/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
   url(r'^',include('generalzone.urls')),
url(r'^studentzone/',include(('studentzone.urls','studentzone'),namespace='studentzone')),
url(r'^teachers/',include(('teachers.urls','teachers'),namespace='teachers')),
    url(r'^director/',include(('director.urls','director'),namespace='director')),
   ]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

Smart-Attendance-Management-System-Using-Facial-Recognition-main/director/urls.py
from django.conf.urls import url
from . import views
urlpatterns=[
    url(r'^$',views.direchome,name='direchome'),
    url(r'^createtable',views.createtable,name='createtable'),
    url(r'^savetable',views.savetable,name='savetable'),
    url(r'^deletedepartment/(?P<id>\d+)$',views.deletedepartment,name='deletedepartment'),
    url(r'^createsubject',views.createsubject,name='createsubject'),
    url(r'^showsubject/(?P<id>\d+)$',views.showsubject,name='showsubject'),
    url(r'^savesubject',views.savesubject,name='savesubject'),

]

Smart-Attendance-Management-System-Using-Facial-Recognition-main/teachers/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.views.static import serve
urlpatterns=[
    url(r'^$',views.home,name='home'),
url(r'^capture',views.capture,name='capture'),
url(r'^indexes',views.indexes,name='indexes'),
url(r'^face_detect',views.face_detect,name='face_detect'),
url(r'^attend',views.attend,name='attend'),
url(r'^viewstudentgroup',views.viewstudentgroup,name='viewstudentgroup'),
url(r'^createstudentgroup/(?P<id>\d+)$',views.createstudentgroup,name='createstudentgroup'),
url(r'^savestudentgroup',views.savestudentgroup,name='savestudentgroup'),
url(r'^viewattendance',views.viewattendance,name='viewattendance'),
url(r'^download',views.download,name='download'),
url(r'^awesome_method',views.awesome_method,name='awesome_method'),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Smart-Attendance-Management-System-Using-Facial-Recognition-main/teachers/models.py
from django.db import models
class Studentgroup(models.Model):
    teachername=models.CharField(max_length=50)
    studentgroup=models.CharField(max_length=50)
    startroll=models.IntegerField(max_length=50,default=0)
    endroll=models.IntegerField(max_length=50,default=0)
    startrolllate=models.IntegerField(max_length=50,default=0)
    endrolllate=models.IntegerField(max_length=50,default=0)


# Create your models here.

Smart-Attendance-Management-System-Using-Facial-Recognition-main/teachers/views.py
from django.shortcuts import render,redirect,render_to_response
from . import script
from . import detect
from . import attendances
from django.conf import settings
import datetime
import os
from django.core.exceptions import ObjectDoesNotExist
import pyexcel as p
from director.models import Subject
from teachers.models import Studentgroup
from generalzone.models import StudentInfo
import openpyxl
import mimetypes
from django.http import HttpResponse
from wsgiref.util import FileWrapper
from generalzone.models import LoginInfo
from twilio.rest import TwilioRestClient
from django.conf import settings
from django.conf import settings
from django.http import HttpResponse
from twilio.rest import Client
mon=14664
def home(request):
    if request.session['teachid']:
        x=request.session['teachid']
        st=Subject.objects.filter(teachername=x)
        print(st)
        return render(request,'home.html',{'st':st,'x':x})
    else:
        return render(request,'index.html')
def viewstudentgroup(request):
    if request.session['teachid']:
        teachid = request.session['teachid']
        st1 = Studentgroup.objects.filter(teachername=teachid)
        return render(request, 'viewstudentgroup.html', {'st1': st1})
    else:
        return render(request,'index.html')
def createstudentgroup(request,id):
    if request.session['teachid']:
        teachid=request.session['teachid']
        x=id
        print(x)
        return render(request,'createstudentgroup.html',{'x':x})
    else:
        return render(request,'index.html')


def savestudentgroup(request):
    if request.session['teachid']:
        teachid=request.session['teachid']
        studentgroup=request.POST['studentgroup']
        startroll= request.POST['startroll']
        startrolllate= request.POST['startrolllate']
        endroll= request.POST['endroll']
        endrolllate = request.POST['endrolllate']
        st=Studentgroup(studentgroup=studentgroup,teachername=teachid,startroll=startroll,startrolllate=startrolllate,endroll=endroll,endrolllate=endrolllate)
        st.save()
        subjectid = request.POST['subjectid']
        print(subjectid)
        x=Subject.objects.get(id=subjectid)
        x.studentgroup=studentgroup
        x.save(update_fields=["studentgroup"])
        now = datetime.datetime.now()
        today = now.day
        month = now.month
        mn = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October',
              'November', 'December']
        book = None
        for v in range(0,12):
            if not os.path.isdir("./media/Attendances/Semester " + str(x.semester) + "/" + str(x.subjectcode) + "/"):
               os.makedirs("./media/Attendances/Semester " + str(x.semester) + "/" + str(x.subjectcode) + "/")
            if not os.path.isfile(os.path.join("./media/Attendances/Semester "+str(x.semester)+"/"+str(x.subjectcode)+"/",str(mn[v]) + '.xlsx')):
               book = openpyxl.Workbook()
            else:
               book = openpyxl.load_workbook(os.path.join("./media/Attendances/Semester "+str(x.semester)+"/"+str(x.subjectcode)+"/",str(mn[v]) + '.xlsx'))
            sheet=book.active
            loop=int(endroll)-int(startroll)
            for i in range(0,loop+1):
                try:
                    st=StudentInfo.objects.get(rollno=str(i+int(startroll)))
                    if st is not None:
                        sheet.cell(row=int(i+1),column=2).value=st.name
                    else:
                        sheet.cell(row=int(i + 1), column=2).value ="------"
                except ObjectDoesNotExist:
                    print()
                sheet.cell(row=int(i+1), column=1).value =str(i+int(startroll))
                print('xyz')
                book.save(os.path.join("./media/Attendances/Semester " + str(x.semester) + "/" + str(x.subjectcode) + "/",str(mn[v])+'.xlsx'))
        return redirect('teachers:home')
    else:
        return render(request,'index.html')
def capture(request):
    if request.session['teachid']:
        if request.method == "POST":
            py_obj = script.test_code()
            return render(request,'home.html')
    else:
        return render(request,'index.html')
def face_detect(request):
    if request.session['teachid']:
        if request.method == "POST":
            py = detect.recognize()
            return render(request,'home.html')
    else:
        return render(request,'index.html')
def attend(request):
    if request.session['teachid']:
        if request.method == "POST":
            subjectid = request.POST['attendanceId']
            print(subjectid)
            x=Subject.objects.get(id=subjectid)
            print('pqr')
            p=Studentgroup.objects.get(teachername=x.teachername,studentgroup=x.studentgroup)
            print('mno')
            print(x.semester)
            print(x.subjectcode)
            print(p.startroll)
            print(p.endroll)
            py = attendances.test_attend(x.semester,x.subjectcode,p.startroll,p.endroll)
            st = Subject.objects.filter(teachername=x)
            x.attendanceDateTime = str(str(datetime.datetime.now().strftime("%Y/%m/%d"))+"    "+str(datetime.datetime.now().strftime("%H:%M:%S")))
            x.save(update_fields=['attendanceDateTime'])
            return redirect('teachers:home')
            x = request.session['teachid']

            print(st)
            print("sddfgh")
            print(mon)
            print("asdfg")

            return render(request, 'home.html', {'st': st, 'x': x, 'attendanceDateTime': attendanceDateTime})
    else:
        return render(request,'index.html')
def viewattendance(request):
    if request.session['teachid']:
        now = datetime.datetime.now()
        today = now.day
        month = now.month
        year=now.year
        mn = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October',
              'November', 'December']
        book = None
        viewId = request.POST['viewAttendance']
        x=Subject.objects.get(id=viewId)
        """if not os.path.isdir("./media/Attendances/Semester " + str(x.semester) + "/" + str(x.subjectcode) + "/"):
           os.makedirs("./media/Attendances/Semester " + str(x.semester) + "/" + str(x.subjectcode) + "/")
        if not os.path.isfile(os.path.join("./media/Attendances/Semester "+str(x.semester)+"/"+str(x.subjectcode)+"/",str(mn[int(month)]) + '.xlsx')):
           book = openpyxl.Workbook()
        else:
           book = openpyxl.load_workbook(os.path.join("./media/Attendances/Semester "+str(x.semester)+"/"+str(x.subjectcode)+"/",str(mn[int(month)]) + '.xlsx'))
        sheet=book.active"""
        wb = openpyxl.load_workbook(os.path.join("./media/Attendances/Semester "+str(x.semester)+"/"+str(x.subjectcode)+"/",str(mn[int(month)-1]) + '.xlsx'))
        worksheet = wb.active
        excel_data = list()
        dates=[]
        for row in worksheet.iter_rows():
            i=1
            for cell in row:
                dates.append(str(i))
                i=i+1
                if(i==33):
                    break
            break
        for row in worksheet.iter_rows():
            row_data = list()
            for cell in row:
                row_data.append(str(cell.value))
            excel_data.append(row_data)
        st = Subject.objects.filter(id=viewId)
        return render(request, 'home.html', {"excel_data": excel_data,"dates":dates,'st':st})
    else:
        return render(request,'index.html')
def download(request):
    viewId=request.POST['download']
    x = Subject.objects.get(id=viewId)
    print(x.semester)
    print(x.semester)
    files=list()
    mn = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October',
          'November', 'December']
    t=[0,1,2,3,4,5,6,7,8,9,10,11,12]
    for v in range(0, 12):
        if not os.path.isdir("./media/Attendances/Semester " + str(x.semester) + "/" + str(x.subjectcode) + "/"):
            os.makedirs("./media/Attendances/Semester " + str(x.semester) + "/" + str(x.subjectcode) + "/")
        if os.path.isfile(
            os.path.join("./media/Attendances/Semester " + str(x.semester) + "/" + str(x.subjectcode) + "/",
                         str(mn[v]) + '.xlsx')):
            files.append(str("../media/Attendances/Semester " + str(x.semester) + "/" + str(x.subjectcode) + "/"+
                         str(mn[v]) + '.xlsx'))
            print(t[0])
    print(files[0])


    return render(request,'download.html',{'files':files,'x':x,'mn':mn,'t':t})
def awesome_method(request):
    message_to_broadcast = ("Aur bhai kya haal chaal "
                            "yet? Grab it here: https://www.twilio.com/quest")
    client = Client("ACf9cac7ad6f9f4201015286316281e2c7","54e9f910139b89c2b9b9f042e85d4307")
    for recipient in settings.SMS_BROADCAST_TO_NUMBERS:
        if recipient:
            client.messages.create(to='+917985445472',
                                   from_="+12512441061",
                                   body=message_to_broadcast)
    return HttpResponse("messages sent to students with short attendance!", 200)
def indexes(request):
    if request.session['teachid']:
        return render(request,'indexes.html')
    else:
        return render(request,'index.html')

Smart-Attendance-Management-System-Using-Facial-Recognition-main/teachers/templates/createstudentgroup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Bootstrap 4 Sticky Top Navbar</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>

<form class="form-horizontal" action="{%url 'teachers:savestudentgroup' %}"  method="post">

                {% csrf_token %}


                <div class="form-group">
                    <div class="row">
                    <label class="control-label col-sm-2" for="studentgroup"><b>Student Group Name:</b></label>

    <input type="text" class="form-control col-sm-5" name="studentgroup" id="studentgroup" placeholder="Enter Student Group Name" required>


                </div>

                </div>

                <div class="form-group">
                    <div class="row">
                    <label class="control-label col-sm-2" for="startroll"><b>Start roll no:</b></label>

    <input type="text" class="form-control col-sm-5" name="startroll" id="startroll" placeholder="Enter Start roll no:" required>


                </div>

                </div>
    <div class="form-group">
                    <div class="row">
                    <label class="control-label col-sm-2" for="endroll"><b>Ending roll no:</b></label>

    <input type="text" class="form-control col-sm-5" name="endroll" id="endroll" placeholder="Enter Ending roll no:" required>


                </div>

                </div>
        <div class="form-group">
                    <div class="row">
                    <label class="control-label col-sm-2" for="startrolllate"><b>Start roll no lateral entry:</b></label>

    <input type="text" class="form-control col-sm-5" name="startrolllate" id="startrolllate" placeholder="Enter Start roll no for lateral entry:" required>


                </div>

                </div>
    <div class="form-group">
                    <div class="row">
                    <label class="control-label col-sm-2" for="endrolllate"><b>Ending roll no lateral entry:</b></label>

    <input type="text" class="form-control col-sm-5" name="endrolllate" id="endrolllate" placeholder="Enter Ending roll no for lateral entry:" required>


                </div>

                </div>
     <input type="hidden" name="subjectid" value="{{x}}">


                    <div class="col-sm-5">
                        <button type="submit" class="btn btn-success">
                            Submit
                        </button>
                    </div>



            </form>

</body>
</html>

Smart-Attendance-Management-System-Using-Facial-Recognition-main/teachers/templates/download.html
<!DOCTYPE html>
<html lang="en">
{% load static%}
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Bootstrap 4 Sticky Top Navbar</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.js"></script>
    <style>
    div.scrollmenu {
  background-color: #333;
  overflow: auto;
  white-space: nowrap;
}

div.scrollmenu a {
  display: inline-block;

  text-align: center;
  padding: 14px;
  text-decoration: none;
}


        /* The heart of the matter */

        .horizontal-scrollable > .scrollmenu {
            overflow-x: auto;

        }

        .horizontal-scrollable > .scrollmenu > .col-xs-4 {
            display: inline-block;
            float: none;
        }
        /* Decorations */

        .col-xs-4 {

            font-size: 24px;
            padding-bottom: 20px;
            padding-top: 18px;
        }

        .col-xs-4:nth-child(2n+1) {

        }

        .col-xs-4:nth-child(2n+2) {

        }
    </style>
</head>
<body>




 <div class="table-responsive" class="container-fluid">

      <table border="1" style="margin:0px auto;width:100%" class="table">
          <thead class="table-dark" style="text-align:center">
             <tr>
                 <td>Subject Name</td>
                 <td>Branch</td>
                 <td>Semester</td>
                 <td>Subject Code</td>
                 <td>Teacher's Name</td>
                 <td>Student Group</td>

             </tr>
          </thead>


          <tbody class="table-hover">

               <tr class="table-primary" style="text-align:center">
                   <td>{{x.subjectname}}</td>
                   <td>{{x.dept}}</td>
                   <td>{{x.semester}}</td>
                   <td>{{x.subjectcode}}</td>
                   <td>{{x.teachername}}</td>
                   <td>{%ifequal x.studentgroup ''%}
                       <a href="{%url 'teachers:createstudentgroup' x.id%}">Add Student Group</a>
                       {%endifequal%}
                       {{x.studentgroup}}
                       </td>
               </tr>

          </tbody>

            </table>
           <br/>
</div>



 <div class="table-responsive" class="container-fluid">
       <table border="1" style="margin:0px auto;width:100%" class="table">

          <thead class="table-dark" style="text-align:center">
          <tr><td>Month</td><td>File Download</td></tr>
          </thead>
           <tbody class="table-hover">


{%if files.0 is not None %}
           <tr class="table-primary" style="text-align:center"><td>{{mn.0}}</td><td><a href="{{files.0}}" download="{{files.0}}">Download</a> </td></tr>{%endif%}
{%if files.1 is not None %}
<tr class="table-primary" style="text-align:center"><td>{{mn.1}}</td><td><a href="{{files.1}}" download="{{files.1}}">Download</a> </td></tr>{%endif%}
    {%if files.2 is not None %}
<tr class="table-primary" style="text-align:center"><td>{{mn.2}}</td><td><a href="{{files.2}}" download="{{files.2}}">Download</a> </td></tr>{%endif%}
{%if files.3 is not None %}
<tr class="table-primary" style="text-align:center"><td>{{mn.3}}</td><td><a href="{{files.3}}" download="{{files.3}}">Download</a> </td></tr>{%endif%}
{%if files.4 is not None %}
<tr class="table-primary" style="text-align:center"><td>{{mn.4}}</td><td><a href="{{files.4}}" download="{{files.4}}">Download</a> </td></tr>{%endif%}
{%if files.5 is not None %}
<tr class="table-primary" style="text-align:center"><td>{{mn.5}}</td><td><a href="{{files.5}}" download="{{files.5}}">Download</a> </td></tr>{%endif%}
{%if files.6 is not None %}
<tr class="table-primary" style="text-align:center"><td>{{mn.6}}</td><td><a href="{{files.6}}" download="{{files.6}}">Download</a> </td></tr>{%endif%}
       {%if files.7 is not None %}
           <tr class="table-primary" style="text-align:center"><td>{{mn.7}}</td><td><a href="{{files.7}}" download="{{files.7}}">Download</a> </td></tr>{%endif%}
{%if files.8 is not None %}
<tr class="table-primary" style="text-align:center"><td>{{mn.8}}</td><td><a href="{{files.8}}" download="{{files.8}}">Download</a> </td></tr>{%endif%}
{%if files.9 is not None %}
<tr class="table-primary" style="text-align:center"><td>{{mn.9}}</td><td><a href="{{files.9}}" download="{{files.9}}">Download</a> </td></tr>{%endif%}
          {%if files.10 is not None %}
           <tr class="table-primary" style="text-align:center"><td>{{mn.10}}</td><td><a href="{{files.10}}" download="{{files.10}}">Download</a> </td></tr>{%endif%}
{%if files.11 is not None %}
<tr class="table-primary" style="text-align:center"><td>{{mn.11}}</td><td><a href="{{files.11}}" download="{{files.11}}">Download</a> </td></tr>{%endif%}



           </tbody>
       </table>
     </div>







</body>
</html>

Smart-Attendance-Management-System-Using-Facial-Recognition-main/teachers/templates/handsontable.html
<html><head>
 <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/handsontable/0.31.0/handsontable.full.min.css">
 <script src="https://cdnjs.cloudflare.com/ajax/libs/handsontable/0.31.0/handsontable.full.min.js"></script>
 <style>
 body{font-family:Helvetica,sans-serif;margin:2 0 0 0}.tab{margin-bottom:0 !important;text-align:center;list-style:none;padding:0 0 0 10px;line-height:24px;height:26px;overflow:hidden;font-size:12px;font-family:verdana;position:relative;margin:0}.tab li{margin-left:0 !important;float:left;height:24px;border:1px solid #aaa;background:#d1d1d1;background:linear-gradient(top, #ececec 50%, #d1d1d1);display:inline-block;position:relative;z-index:0;border-top-left-radius:6px;border-top-right-radius:6px;box-shadow:0 3px 3px rgba(0,0,0,0.4),inset 0 1px 0 #fff;text-shadow:0 1px #fff;margin:0 -5px;padding:0 20px}.tab li.active{background:#fff;color:#333;z-index:2}.tab li:before{left:-6px;border-width:0 1px 1px 0;box-shadow:2px 2px 0 #d1d1d1}.tab li:after{right:-6px;border-width:0 0 1px 1px;box-shadow:-2px 2px 0 #d1d1d1}.tab a{color:#555;text-decoration:none}.tab:before{position:absolute;content:" ";width:100%;bottom:0;left:0;border-bottom:1px solid #aaa;z-index:1}.tabcontent{margin-top:-1px}
 </style>
</head>
 <body>
 hello
</body>
</html>

Smart-Attendance-Management-System-Using-Facial-Recognition-main/teachers/templates/viewstudentgroup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Bootstrap 4 Sticky Top Navbar</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="table-responsive">
             <center><h3>Student Group</h3></center>
      <table border="1" style="margin:0px auto;width:90%" class="table">
          <thead class="table-dark" style="text-align:center">
             <tr>
                 <td>studentgroup</td>
                 <td>teachername</td>
                 <td>startroll</td>
                 <td>endroll</td>
                 <td>startrolllate</td>
                 <td>endrolllate</td>
                 <td>choose</td>
             </tr>
          </thead>
          {% for e in st1%}

          <tbody class="table-hover">
               <tr class="table-primary" style="text-align:center">
                   <td>{{e.studentgroup}}</td>
                 <td>{{e.teachername}}</td>
                 <td>{{e.startroll}}</td>
                 <td>{{e.endroll}}</td>
                 <td>{{e.startrolllate}}</td>
                 <td>{{e.endrolllate}}</td>
                 <td><a href="#">choose</a></td>
               </tr>
          </tbody>


{%endfor%}
            </table>
           <br/>
</div>
</body>
</html>