Smart-Attendance-Management-System-Using-Facial-Recognition-main/CollegeAutomation/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
   url(r'^',include('generalzone.urls')),
url(r'^studentzone/',include(('studentzone.urls','studentzone'),namespace='studentzone')),
url(r'^teachers/',include(('teachers.urls','teachers'),namespace='teachers')),
    url(r'^director/',include(('director.urls','director'),namespace='director')),
   ]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

Smart-Attendance-Management-System-Using-Facial-Recognition-main/director/urls.py
from django.conf.urls import url
from . import views
urlpatterns=[
    url(r'^$',views.direchome,name='direchome'),
    url(r'^createtable',views.createtable,name='createtable'),
    url(r'^savetable',views.savetable,name='savetable'),
    url(r'^deletedepartment/(?P<id>\d+)$',views.deletedepartment,name='deletedepartment'),
    url(r'^createsubject',views.createsubject,name='createsubject'),
    url(r'^showsubject/(?P<id>\d+)$',views.showsubject,name='showsubject'),
    url(r'^savesubject',views.savesubject,name='savesubject'),

]

Smart-Attendance-Management-System-Using-Facial-Recognition-main/director/models.py
from django.db import models
class Department(models.Model):
    deptname=models.CharField(max_length=50)
    deptcode=models.CharField(max_length=10)
    depthod=models.CharField(max_length=70)
    course=models.CharField(max_length=50)
class Subject(models.Model):
    subjectname=models.CharField(max_length=50)
    semester=models.CharField(max_length=50)
    dept=models.CharField(max_length=50)
    subjectcode=models.CharField(max_length=50)
    teachername=models.CharField(max_length=50)
    studentgroup=models.CharField(max_length=50)
    attendanceDateTime=models.CharField(max_length=50)

Smart-Attendance-Management-System-Using-Facial-Recognition-main/director/views.py
from django.shortcuts import render,redirect,reverse
from .models import Department,Subject
from generalzone.models import LoginInfo
def direchome(request):
    if (request.session['direcid']):
        dept=Department.objects.all()
        return render(request,'home1.html',{'dept':dept})
    else:
        return render(request,'index.html')
# Create your views here.
def createtable(request):
    if(request.session['direcid']):
        return render(request,'createtable.html')
    else:
        return render(request,'index.html')
def savetable(request):
    if(request.session['direcid']):
        deptname=request.POST['deptname']
        deptcode=request.POST['deptcode']
        depthod=request.POST['depthod']
        course=request.POST['course']
        re=Department(deptname=deptname,deptcode=deptcode,depthod=depthod,course=course)
        re.save()
        return redirect('director:direchome')
    else:
        return render(request,'index.html')
def deletedepartment(request,id):
    if request.session['direcid']:
        e=Department.objects.get(id=id)
        e.delete()
        return redirect('director:direchome')
    else:
        return render(request,'index.html')
def createsubject(request):
    if request.session['direcid']:
        x=LoginInfo.objects.filter(usertype='teacher')
        y=Department.objects.all()
        context={'x':x,'y':y}
        return render(request,'createsubject.html',context)
    else:
        return render(request,'index.html')
def savesubject(request):
    if request.session['direcid']:
        subjectname=request.POST['subjectname']
        deptname=request.POST['deptname']
        semester=request.POST['semester']
        subjectcode=request.POST['subjectcode']
        teachername=request.POST['teachername']
        de=Subject(subjectname=subjectname,dept=deptname,semester=semester,subjectcode=subjectcode,teachername=teachername)
        de.save()
        e = Department.objects.get(deptname=deptname)
        return redirect('director:showsubject',e.id)
    else:
        return render(request,'index.html')
def showsubject(request,id):
    if request.session['direcid']:
          e=Department.objects.get(id=id)
          ss=Subject.objects.filter(dept=e.deptname)
          p=''
          if(e.deptname=="CSE"):
              p='Computer Science & Engineering'
          elif(e.deptname=="EE"):
              p="Electrical Engineering"
          elif(e.deptname=="EL"):
              p="Electronic Engineering"

          return render(request,'showsubject.html',{'ss':ss,'p':p})
    else:
        return render(request,'index.html')

Smart-Attendance-Management-System-Using-Facial-Recognition-main/director/templates/createsubject.html
<!DOCTYPE html>
<html lang="en">
{% load static%}
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Bootstrap 4 Sticky Top Navbar</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<body>

<form class="form-horizontal" action="{%url 'director:savesubject' %}"  method="post">

                {% csrf_token %}


                <div class="form-group">
                    <div class="row">
                    <label class="control-label col-sm-2" for="subjectname"><b>Subject Name:</b></label>

    <input type="text" class="form-control col-sm-5" name="subjectname" id="subjectname" placeholder="Enter Subject Name" required>


                </div>

                </div>




    <div class="form-group">
        <div class="row">
                    <label class="control-label col-sm-2" for="deptname"><b>Department</b></label>

    <select class="form-control col-sm-5" id="deptname" name="deptname" >{% for y in y %}
  <option class="form-control col-sm-5"  value="{{y.deptname}}">{{y.deptname}}</option>
     {%endfor%}</select>


        </div>   </div>

    <div class="form-group">
        <div class="row">
                    <label class="control-label col-sm-2" for="semester"><b>Semester</b></label>

    <input type="text" class="form-control col-sm-5" name="semester" id="semester" placeholder="Enter Semester" required>


        </div>   </div>

      <div class="form-group">
        <div class="row">
                    <label class="control-label col-sm-2" for="subjectcode"><b>Subject Code</b></label>

    <input type="text" class="form-control col-sm-5" name="subjectcode" id="subjectcode" placeholder="Enter Subject Code" required>


        </div>   </div>


                <div class="form-group">
                    <div class="row">
                    <label class="control-label col-sm-2" for="teachername"><b>Teacher's Name</b></label>
 <select class="form-control col-sm-5" id="teachername" name="teachername" >{% for e in x %}
  <option class="form-control col-sm-5"  value="{{e.userid}}">{{e.userid}}</option>
     {%endfor%}</select>


</div>
                </div>









                    <div class="col-sm-5"><input type="hidden" name="id" value="{{id}}"/>
                        <button type="submit" class="btn btn-success">
                            Add Subject
                        </button>
                    </div>

</form>

</body>
</html>

Smart-Attendance-Management-System-Using-Facial-Recognition-main/director/templates/createtable.html
<!DOCTYPE html>
<html lang="en">
{% load static%}
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Bootstrap 4 Sticky Top Navbar</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<body>

<form class="form-horizontal" action="{%url 'director:savetable' %}"  method="post">

                {% csrf_token %}


                <div class="form-group">
                    <div class="row">
                    <label class="control-label col-sm-2" for="deptname"><b>Department Name:</b></label>

    <input type="text" class="form-control col-sm-5" name="deptname" id="deptname" placeholder="Enter Department Name" required>


                </div>

                </div>




    <div class="form-group">
        <div class="row">
                    <label class="control-label col-sm-2" for="deptcode"><b>Department Code</b></label>

    <input type="text" class="form-control col-sm-5" name="deptcode" id="deptcode" placeholder="Enter Department Code" required>


        </div>   </div>

      <div class="form-group">
        <div class="row">
                    <label class="control-label col-sm-2" for="depthod"><b>Department HOD</b></label>

    <input type="text" class="form-control col-sm-5" name="depthod" id="depthod" placeholder="Enter Department HOD" required>


        </div>   </div>


                <div class="form-group">
                    <div class="row">
                    <label class="control-label col-sm-2" for="course"><b>Course</b></label>

    <input type="text"  class="form-control col-sm-5" name="course" id="course" placeholder="Enter Course" required>

</div>
                </div>







                    <div class="col-sm-5">
                        <button type="submit" class="btn btn-success">
                            Submit
                        </button>
                    </div>



            </form>

</body>
</html>

Smart-Attendance-Management-System-Using-Facial-Recognition-main/director/templates/home1.html
<!DOCTYPE html>
<html lang="en">
{% load static%}
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Bootstrap 4 Sticky Top Navbar</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>
       <div class="table-responsive">
        <table border="1" style="margin:0px auto;width:90%" class="table" >
          <thead class="table-dark" style="text-align:center">
           <tr>
               <th>Department Name</th>
               <th>Department Code</th>
               <th>Department HOD</th>
               <th>Course</th>
               <th>Go</th>
               <th>Delete</th>

           </tr></thead>
            {% for e in dept %}
              <tbody class="table-hover">
                <tr class="table-primary" style="text-align:center">

                    <td>{{e.deptname}}</td>
                    <td>{{e.deptcode}}</td>
                    <td>{{e.depthod}}</td>
                    <td>{{e.course}}</td>
                    <td><a style="font-weight:bold;" href="{%url 'director:showsubject' e.id%}">Go</a></td>
                    <td><a style="font-weight:bold;" href="{%url 'director:deletedepartment' e.id%}">Delete</a></td>
                </tr>
              </tbody>
            {%endfor%}
        </table>
            </div>
       <br/>
       <br/>
       <center>
<form action="{% url 'director:createtable' %}" method="post">
    {%csrf_token%}
    <button type="submit" name="createtable" id="createtable">
   Create Table
    </button>
</form>
</center>
</body>
</html>

Smart-Attendance-Management-System-Using-Facial-Recognition-main/director/templates/showsubject.html
<!DOCTYPE html>
<html lang="en">
{% load static%}
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Bootstrap 4 Sticky Top Navbar</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>


       <!---------------------------------------------------------------------------------------!>
       <!--------------------------------------------------------------------------------------->


        <div class="table-responsive">
             <center><h3>{{p}}</h3></center>
      <table border="1" style="margin:0px auto;width:90%" class="table">
          <thead class="table-dark" style="text-align:center">
             <tr>
                 <td>Subject Name</td>
                 <td>Branch</td>
                 <td>Semester</td>
                 <td>Subject Code</td>
                 <td>Teacher's Name</td>
                 <td>Student Group</td>
             </tr>
          </thead>
          {% for e in ss%}

          <tbody class="table-hover">

               <tr class="table-primary" style="text-align:center">
                   <td>{{e.subjectname}}</td>
                   <td>{{e.dept}}</td>
                   <td>{{e.semester}}</td>
                   <td>{{e.subjectcode}}</td>
                   <td>{{e.teachername}}</td>
                   <td>{{e.studentgroup}}</td>

               </tr>

          </tbody>


{%endfor%}
            </table>
           <br/>
</div>

       <br/>
       <br/>

       <!---------------------------------------------------------------------------------------->
       <!---------------------------------------------------------------------------------------->


       <!---------------------------------------------------------------------------------------->
       <!---------------------------------------------------------------------------------------->


          <center>
<form action="{%url 'director:createsubject'%}" method="post">
{%csrf_token%}
    <button type="submit" name="addsubject" id="addsubject">Add Subject</button>
</form>
                 </center>
</body>
</html>